<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-08T08:55:59 IST" name="Suite" finished-at="2023-06-08T08:56:16 IST" duration-ms="17011">
    <groups>
    </groups>
    <test started-at="2023-06-08T08:55:59 IST" name="Test" finished-at="2023-06-08T08:56:16 IST" duration-ms="17011">
      <class name="com.learnautomatiom.testcases.LoginTest">
        <test-method is-config="true" signature="setupApplication()[pri:0, instance:com.learnautomatiom.testcases.LoginTest@62010f5c]" started-at="2023-06-08T08:55:59 IST" name="setupApplication" finished-at="2023-06-08T08:56:09 IST" duration-ms="9948" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupApplication -->
        <test-method signature="loginToApp(java.lang.String,java.lang.String)[pri:0, instance:com.learnautomatiom.testcases.LoginTest@62010f5c]" started-at="2023-06-08T08:56:10 IST" name="loginToApp" data-provider="users" finished-at="2023-06-08T08:56:16 IST" duration-ms="5854" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Mukesh@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mukesh@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error messages is displayed as expected expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error messages is displayed as expected expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.learnautomatiom.testcases.LoginTest.loginToApp(LoginTest.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApp -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.learnautomatiom.testcases.LoginTest@62010f5c]" started-at="2023-06-08T08:56:16 IST" name="tearDown" finished-at="2023-06-08T08:56:16 IST" duration-ms="139" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.learnautomatiom.testcases.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
